[package]
name = "bridgekit-mock-tauri-app"
version = "0.1.0"
edition.workspace = true
publish = false

[build-dependencies]
tauri-build = "2.6.3"

[dependencies]
bridgekit = { path = "../../../crates/bridgekit" }
serde_json = "1.0.150"
tauri = "2.11.5"
tauri-plugin-bridgekit = { path = "../../../crates/tauri-plugin-bridgekit" }
